### ISSUE TITLE
Look into audio formats & filesizes

### ISSUE THREAD

**Issue by benfoxall** [remotehack/live#3]
On the default settings from audacity/ffmpeg, it's about 1mb a minute for the m4a files.

With hackside chats, it gets pretty big.  

Perhaps we could look into running them through a script or something?

**Comment by omgmog** [comment]
Some notes from some podcast publishing platforms:

https://help.libsynsupport.com/hc/en-us/articles/360040796152-Recommended-Audio-File-Formats-Encoding

> **Audio Encoding**
> Spoken Word Shows:
> Stereo Bit Rate - 192 kbps or lower (In Mono this gets cut in half)
> Sample Rate - 44.1 kHz
> Channels - Mono

> Your editing software may offer a checkbox for VBR or Variable Bit Rate. Do not check this box, your bit rate needs to be constant. The reason behind this is variable bit rate will change how different players and systems scan the file, and they often will either be incompatible with VBR completely, or at the very least will get the duration of the file incorrect causing the file to end up cut off towards the end.

> Not all podcast directories support M4A, but they all support MP3. For greatest compatibility, upload MP3 files for episodes distributing to podcast directories.


https://help.simplecast.com/en/articles/786134-audio-encoding-tips


> **What bit rate do we recommend?**
> 128kbps or less 
> Note: Higher bit rate = higher quality and larger file size. The goal is to balance quality and file size. Tip: Export your episodes at different bit rates (128, 96, 64 kbps) and use your ears to test the quality to try and get the highest quality with the smallest file size. 

> **Mono or Stereo?**
> Mono is the most common for podcasters and recommended for spoken word podcasts and people talking (solo shows, interviews, round table/panel discussions). Mono is fine even if you have music at the intro or outro of your episodes. Mono is a good choice for most podcasts as the file size is smaller and the quality will be comparable to stereo. Mono uses one channel so what you hear in your left ear is the same as the right. 

> **What about Sample Rate, Bit Depth & mp3 Type?:**
> Sample Rate: 44.1 kHz 
> Bit Depth: 32-bit float or 24-bit 
> mp3 Type: Constant Bit Rate (CBR)

So you probably want to be producing 128kbps/44.1 kHz/CBR mp3, and perhaps providing similar quality ogg/m4a to improve your coverage. Reasonably, a one hour episode should hit about 50mb.
